# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "minitest"

# demonstation
gem "mongoid" # Mongo Database Abstraction
gem "faker" # Test Data Generator
gem "pry" # Debugger
