# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "minitest"

gem "mongoid" # MongoDB database abstraction
gem "faker" # Dummy Data Generators
gem "pry" # Debugger
